version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY="6de4380419ca9bb075519474238b558a"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
